version: '3.8'
services:
  gateway:
    build: ./gateway
    container_name: shareIt-gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    container_name: shareIt-server-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ru-base
      - POSTGRES_USER=newuser
      - POSTGRES_PASSWORD=pass
      - TZ=Europe/Moscow
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:13.7-alpine
    container_name: shareIt-DataBase-container
    ports:
      - "6541:5432"
    volumes:
    - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ru-base
      - POSTGRES_USER=newuser
      - POSTGRES_PASSWORD=pass



